<?php
namespace UCL\StudyBundle\Entity;

use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity
 * @ORM\Table(name="study_datauploadjob")
 */
class DataUploadJob
{
  /**
   * @ORM\Column(type="string", length=255)
   * @ORM\Id
   * @Assert\File(
   *     mimeTypes = {"application/x-tar", "application/x-bzip2", "application/x-gtar", "application/x-gzip"},
   *     mimeTypesMessage = "The type of the file is invalid ({{ type }}). Please upload the archive generated by your data collection software."
   * )
   */
  protected $file;

   /**
   * @ORM\Column(type="string", length=255)
   * @ORM\Id
   * @Assert\NotBlank(message = "We could not find the participant email this archive is associated with. This is a bug. Please contact the researchers.",)
   * @Assert\Email()
   */
  protected $email;

  function __construct ($email)
  {
    $this->file  = null;
    $this->email = $email;
  }

  public function getFile()
  {
      return $this->file;
  }

  public function setFile($file)
  {
      $this->file = $file;
  }

  public function getEmail()
  {
      return $this->email;
  }

  public function setEmail($email)
  {
      $this->email = $email;
  }
}

?>
