security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      15
        UCL\StudyBundle\Entity\Participant: 
            algorithm: bcrypt
            cost:      15
#            algorithm:            pbkdf2
#            hash_algorithm:       sha512
#            encode_as_base64:     true
#            iterations:           1000
#            key_length:           40

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        entity_provider:
            entity:
                class: UCLStudyBundle:Participant
                property: email

    firewalls:
        application_space:
            anonymous: ~
            pattern:   ^/a/
            context: participant
            simple_form:
                authenticator: email_only_authenticator
                login_path: ucl_study_app_login
                check_path: ucl_study_app_login_check
                always_use_default_target_path: true
                default_target_path: ucl_study_app_logged_in
                csrf_parameter: _csrf_token
                csrf_provider: security.csrf.token_manager
                intention:      authenticate
                success_handler: tga_forum.authentication_success_handler
            logout:
                path:   ucl_study_app_logout
                target: ucl_study_app_login
                success_handler: tga_forum.logout_success_handler
            security: true
            provider: entity_provider
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~
        participant_space:
            anonymous: ~
            pattern:   ^/p/
            context: participant
            simple_form:
                authenticator: email_only_authenticator
                login_path: ucl_study_login
                check_path: ucl_study_login_check
                default_target_path: ucl_study_part_next
                csrf_parameter: _csrf_token
                csrf_provider: security.csrf.token_manager
                intention:      authenticate
                success_handler: tga_forum.authentication_success_handler
            logout:
                path:   ucl_study_logout
                target: ucl_study_logged_out
                success_handler: tga_forum.logout_success_handler
            security: true
            provider: entity_provider
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~
        default:
            anonymous: ~
            pattern:   ~
            context: participant

    access_control:
        - { path: ^/p/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/a/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/p/, roles: IS_AUTHENTICATED_REMEMBERED, requires_channel: https }
        - { path: ^/a/, roles: IS_AUTHENTICATED_REMEMBERED, requires_channel: https }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
