# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    tga_forum.vanilla.class: Tga\ForumBundle\Vanilla\Kernel

services:
    stubborn_authenticator:
        class:     UCL\StudyBundle\Security\StubbornAuthenticator
        arguments: ['@tga_forum.vanilla', '@security.http_utils', "@security.password_encoder"]
    email_only_authenticator:
        class:     UCL\StudyBundle\Security\EmailOnlyAuthenticator
        arguments: ['@tga_forum.vanilla', '@security.http_utils', "@security.password_encoder"]
    participant_upload_progress:
        class:        UCL\StudyBundle\Service\ParticipantUploadProgress
        arguments   : []
        calls:
            - [ setContainer, [ @service_container ] ]
    upload_store:
        class:        UCL\StudyBundle\Service\FileStore
        arguments:    ["%file_store.upload%", @translator]
    screening_store:
        class:        UCL\StudyBundle\Service\FileStore
        arguments:    ["%file_store.screening%", @translator]
    payment_store:
        class:        UCL\StudyBundle\Service\FileStore
        arguments:    ["%file_store.payment%", @translator]

# TODO: not in use yet, but should be implemented in the future to integrate with Launchpad's Web translation service
    translation.loader.po:
        class: Symfony\Component\Translation\Loader\PoFileLoader
        tags:
            - { name: translation.loader, alias: po }
    translation.loader.mo:
        class: Symfony\Component\Translation\Loader\MoFileLoader
        tags:
            - { name: translation.loader, alias: mo }
