# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    stubborn_authenticator:
        class:     UCL\StudyBundle\Security\StubbornAuthenticator
        arguments: ["@security.password_encoder"]
    email_only_authenticator:
        class:     UCL\StudyBundle\Security\EmailOnlyAuthenticator
        arguments: ["@security.password_encoder"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    participant_upload_progress:
        class:        UCL\StudyBundle\Service\ParticipantUploadProgress
        arguments   : []
        calls:
            - [ setContainer, [ @service_container ] ]
    upload_store:
        class:        UCL\StudyBundle\Service\FileStore
        arguments:    ["%file_store.upload%", @translator]
    screening_store:
        class:        UCL\StudyBundle\Service\FileStore
        arguments:    ["%file_store.screening%", @translator]
    payment_store:
        class:        UCL\StudyBundle\Service\FileStore
        arguments:    ["%file_store.payment%", @translator]
    translation.loader.po:
        class: Symfony\Component\Translation\Loader\PoFileLoader
        tags:
            - { name: translation.loader, alias: po }
    translation.loader.mo:
        class: Symfony\Component\Translation\Loader\MoFileLoader
        tags:
            - { name: translation.loader, alias: mo }
